/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-05-13 07:21:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("@import url(http://fonts.googleapis.com/css?family=Vibur);\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  -moz-box-sizing: border-box;\r\n");
      out.write("  -webkit-box-sizing: border-box;\r\n");
      out.write("  font-family: arial;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  background: #FFE4E1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("  color: #000080;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-family: 'Vibur', cursive;\r\n");
      out.write("  font-size: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-form {\r\n");
      out.write("  width: 350px;\r\n");
      out.write("  padding: 40px 30px;\r\n");
      out.write("  background: #FFDEAD;\r\n");
      out.write("  -moz-border-radius: 4px;\r\n");
      out.write("  -webkit-border-radius: 4px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  -moz-transform: translateY(-50%);\r\n");
      out.write("  -ms-transform: translateY(-50%);\r\n");
      out.write("  -webkit-transform: translateY(-50%);\r\n");
      out.write("  transform: translateY(-50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 5px 7px 5px 15px;\r\n");
      out.write("  background: #fff;\r\n");
      out.write("  color: #666;\r\n");
      out.write("  border: 2px solid #ddd;\r\n");
      out.write("  -moz-border-radius: 4px;\r\n");
      out.write("  -webkit-border-radius: 4px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write(".form-control:focus, .form-control:focus + .fa {\r\n");
      out.write("  border-color: #10CE88;\r\n");
      out.write("  color: #10CE88;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group .fa {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: 15px;\r\n");
      out.write("  top: 17px;\r\n");
      out.write("  color: #999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".log-status.wrong-entry {\r\n");
      out.write("  -moz-animation: wrong-log 0.3s;\r\n");
      out.write("  -webkit-animation: wrong-log 0.3s;\r\n");
      out.write("  animation: wrong-log 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".log-status.wrong-entry .form-control, .wrong-entry .form-control + .fa {\r\n");
      out.write("  border-color: #ed1c24;\r\n");
      out.write("  color: #ed1c24;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".log-btn {\r\n");
      out.write("  background: #FFAEC9;\r\n");
      out.write("  dispaly: inline-block;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  border: none;\r\n");
      out.write("  -moz-border-radius: 4px;\r\n");
      out.write("  -webkit-border-radius: 4px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".link {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color: #000080;\r\n");
      out.write("  float: right;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write(".link:hover {\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("  color: #8C918F;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".alert {\r\n");
      out.write("  display: none;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  color: #f00;\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-moz-keyframes wrong-log {\r\n");
      out.write("  0%, 100% {\r\n");
      out.write("    left: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  20% , 60% {\r\n");
      out.write("    left: 15px;\r\n");
      out.write("  }\r\n");
      out.write("  40% , 80% {\r\n");
      out.write("    left: -15px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@-webkit-keyframes wrong-log {\r\n");
      out.write("  0%, 100% {\r\n");
      out.write("    left: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  20% , 60% {\r\n");
      out.write("    left: 15px;\r\n");
      out.write("  }\r\n");
      out.write("  40% , 80% {\r\n");
      out.write("    left: -15px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@keyframes wrong-log {\r\n");
      out.write("  0%, 100% {\r\n");
      out.write("    left: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  20% , 60% {\r\n");
      out.write("    left: 15px;\r\n");
      out.write("  }\r\n");
      out.write("  40% , 80% {\r\n");
      out.write("    left: -15px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>\r\n");
      out.write("<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\r\n");
      out.write("<script src=\"js/index.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #FFE4E1;\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"login-form\">\r\n");
      out.write("  <form name='loginForm' action=\"perform_login\" method='POST'>\r\n");
      out.write("     <h1>BookLand</h1>\r\n");
      out.write("     <div class=\"form-group \">\r\n");
      out.write("       <input type=\"text\" class=\"form-control\" placeholder=\"Username \" id=\"username\" name=\"username\" required>\r\n");
      out.write("       <i class=\"fa fa-user\"></i>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"form-group log-status\">\r\n");
      out.write("       <input type=\"password\" class=\"form-control\" placeholder=\"Password\" id=\"password\" name=\"password\" required>\r\n");
      out.write("       <i class=\"fa fa-lock\"></i>\r\n");
      out.write("     </div>\r\n");
      out.write("      <span class=\"alert\">Invalid Credentials</span>\r\n");
      out.write("      <a class=\"link\" href=\"#\">Lost your password?</a>\r\n");
      out.write("     <button type=\"submit class=\"log-btn\" >Log in</button>\r\n");
      out.write("     </form>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
