/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-05-13 06:57:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Sign Up Form</title>\r\n");
      out.write("<style>\r\n");
      out.write("html, body, div, span, applet, object, iframe,\r\n");
      out.write("h1, h2, h3, h4, h5, h6, p, blockquote, pre,\r\n");
      out.write("a, abbr, acronym, address, big, cite, code,\r\n");
      out.write("del, dfn, em, img, ins, kbd, q, s, samp,\r\n");
      out.write("small, strike, strong, sub, sup, tt, var,\r\n");
      out.write("b, u, i, center,\r\n");
      out.write("dl, dt, dd, ol, ul, li,\r\n");
      out.write("fieldset, form, label, legend,\r\n");
      out.write("table, caption, tbody, tfoot, thead, tr, th, td,\r\n");
      out.write("article, aside, canvas, details, embed,\r\n");
      out.write("figure, figcaption, footer, header, hgroup,\r\n");
      out.write("menu, nav, output, ruby, section, summary,\r\n");
      out.write("time, mark, audio, video {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  font-size: 100%;\r\n");
      out.write("  font: inherit;\r\n");
      out.write("  vertical-align: baseline;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("    background-color: #FFE4E1;\r\n");
      out.write("     line-height: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("article, aside, details, figcaption, figure,\r\n");
      out.write("footer, header, hgroup, menu, nav, section {\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("ol, ul {\r\n");
      out.write("  list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote, q {\r\n");
      out.write("  quotes: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote:before, blockquote:after,\r\n");
      out.write("q:before, q:after {\r\n");
      out.write("  content: '';\r\n");
      out.write("  content: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  border-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".about {\r\n");
      out.write("  margin: 70px auto 40px;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("  width: 260px;\r\n");
      out.write("  font: 10px/18px 'Lucida Grande', Arial, sans-serif;\r\n");
      out.write("  color: #666;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-shadow: 0 1px rgba(255, 255, 255, 0.25);\r\n");
      out.write("  background: #eee;\r\n");
      out.write("  background: rgba(250, 250, 250, 0.8);\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  background-image: -webkit-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.1));\r\n");
      out.write("  background-image: -moz-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.1));\r\n");
      out.write("  background-image: -o-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.1));\r\n");
      out.write("  background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.1));\r\n");
      out.write("  -webkit-box-shadow: inset 0 1px rgba(255, 255, 255, 0.3), inset 0 0 0 1px rgba(255, 255, 255, 0.1), 0 0 6px rgba(0, 0, 0, 0.2);\r\n");
      out.write("  box-shadow: inset 0 1px rgba(255, 255, 255, 0.3), inset 0 0 0 1px rgba(255, 255, 255, 0.1), 0 0 6px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write(".about a {\r\n");
      out.write("  color: #333;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  border-radius: 2px;\r\n");
      out.write("  -webkit-transition: background 0.1s;\r\n");
      out.write("  -moz-transition: background 0.1s;\r\n");
      out.write("  -o-transition: background 0.1s;\r\n");
      out.write("  transition: background 0.1s;\r\n");
      out.write("}\r\n");
      out.write(".about a:hover {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  background: #fafafa;\r\n");
      out.write("  background: rgba(255, 255, 255, 0.7);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".about-links {\r\n");
      out.write("  height: 30px;\r\n");
      out.write("}\r\n");
      out.write(".about-links > a {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  line-height: 30px;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".about-author {\r\n");
      out.write("  margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write(".about-author > a {\r\n");
      out.write("  padding: 1px 3px;\r\n");
      out.write("  margin: 0 -1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  font: 13px/20px 'Helvetica Neue', Helvetica, Arial, sans-serif;\r\n");
      out.write("  color: #404040;\r\n");
      out.write("  background: #FFE4E1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sign-up {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  margin: 50px auto;\r\n");
      out.write("  width: 280px;\r\n");
      out.write("  padding: 33px 25px 29px;\r\n");
      out.write("  background: white;\r\n");
      out.write("  border-bottom: 1px solid #c4c4c4;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  -webkit-box-shadow: 0 1px 5px rgba(0, 0, 0, 0.25);\r\n");
      out.write("  box-shadow: 0 1px 5px rgba(0, 0, 0, 0.25);\r\n");
      out.write("}\r\n");
      out.write(".sign-up:before, .sign-up:after {\r\n");
      out.write("  content: '';\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 1px;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  height: 10px;\r\n");
      out.write("  background: inherit;\r\n");
      out.write("  border-bottom: 1px solid #d2d2d2;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write(".sign-up:after {\r\n");
      out.write("  bottom: 3px;\r\n");
      out.write("  border-color: #dcdcdc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sign-up-title {\r\n");
      out.write("  margin: -25px -25px 25px;\r\n");
      out.write("  padding: 15px 25px;\r\n");
      out.write("  line-height: 35px;\r\n");
      out.write("  font-size: 26px;\r\n");
      out.write("  font-weight: 300;\r\n");
      out.write("  color: #aaa;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-shadow: 0 1px rgba(255, 255, 255, 0.75);\r\n");
      out.write("  background: #f7f7f7;\r\n");
      out.write("}\r\n");
      out.write(".sign-up-title:before {\r\n");
      out.write("  content: '';\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  height: 8px;\r\n");
      out.write("  background: #c4e17f;\r\n");
      out.write("  border-radius: 5px 5px 0 0;\r\n");
      out.write("  background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("  background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("  background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("  background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("  font-family: inherit;\r\n");
      out.write("  color: inherit;\r\n");
      out.write("  -webkit-box-sizing: border-box;\r\n");
      out.write("  -moz-box-sizing: border-box;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sign-up-input {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  margin-bottom: 25px;\r\n");
      out.write("  padding: 0 15px 2px;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  background: white;\r\n");
      out.write("  border: 2px solid #ebebeb;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  -webkit-box-shadow: inset 0 -2px #ebebeb;\r\n");
      out.write("  box-shadow: inset 0 -2px #ebebeb;\r\n");
      out.write("}\r\n");
      out.write(".sign-up-input:focus {\r\n");
      out.write("  border-color: #62c2e4;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  -webkit-box-shadow: inset 0 -2px #62c2e4;\r\n");
      out.write("  box-shadow: inset 0 -2px #62c2e4;\r\n");
      out.write("}\r\n");
      out.write(".lt-ie9 .sign-up-input {\r\n");
      out.write("  line-height: 48px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sign-up-button {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  vertical-align: top;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 54px;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  font-size: 22px;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.25);\r\n");
      out.write("  background: #f0776c;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  border-bottom: 2px solid #d76b60;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  -webkit-box-shadow: inset 0 -2px #d76b60;\r\n");
      out.write("  box-shadow: inset 0 -2px #d76b60;\r\n");
      out.write("}\r\n");
      out.write(".sign-up-button:active {\r\n");
      out.write("  top: 1px;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  -webkit-box-shadow: none;\r\n");
      out.write("  box-shadow: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #FFE4E1;\">\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("  <div>\r\n");
      out.write("<form class=\"sign-up\" action=\"successForm\">\r\n");
      out.write("  <h1 class=\"sign-up-title\">Sign up in seconds</h1>\r\n");
      out.write("    <input type=\"text\" class=\"sign-up-input\" placeholder=\"What's your username?\" autofocus required>\r\n");
      out.write("    <input type=\"password\" class=\"sign-up-input\" placeholder=\"Choose a password\" required>\r\n");
      out.write("     <input type=\"text\" class=\"sign-up-input\" placeholder=\"Your e-mail?\" required>\r\n");
      out.write("      <input type=\"text\" class=\"sign-up-input\" placeholder=\"Your contact number?\" required>\r\n");
      out.write("    <input type=\"submit\" value=\"Sign me up!\" class=\"sign-up-button\">\r\n");
      out.write("  </form>\r\n");
      out.write("  <div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
